/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedPortfolioRouteImport } from './routes/_protected/portfolio'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedDashboardTransactionIndexRouteImport } from './routes/_protected/dashboard/transaction/index'
import { Route as ProtectedDashboardPortfolioIndexRouteImport } from './routes/_protected/dashboard/portfolio/index'
import { Route as ProtectedDashboardPortfolioIdRouteImport } from './routes/_protected/dashboard/portfolio/$id'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPortfolioRoute = ProtectedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardTransactionIndexRoute =
  ProtectedDashboardTransactionIndexRouteImport.update({
    id: '/dashboard/transaction/',
    path: '/dashboard/transaction/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardPortfolioIndexRoute =
  ProtectedDashboardPortfolioIndexRouteImport.update({
    id: '/dashboard/portfolio/',
    path: '/dashboard/portfolio/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardPortfolioIdRoute =
  ProtectedDashboardPortfolioIdRouteImport.update({
    id: '/dashboard/portfolio/$id',
    path: '/dashboard/portfolio/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/portfolio': typeof ProtectedPortfolioRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/portfolio/$id': typeof ProtectedDashboardPortfolioIdRoute
  '/dashboard/portfolio': typeof ProtectedDashboardPortfolioIndexRoute
  '/dashboard/transaction': typeof ProtectedDashboardTransactionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/portfolio': typeof ProtectedPortfolioRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/dashboard/portfolio/$id': typeof ProtectedDashboardPortfolioIdRoute
  '/dashboard/portfolio': typeof ProtectedDashboardPortfolioIndexRoute
  '/dashboard/transaction': typeof ProtectedDashboardTransactionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_protected/portfolio': typeof ProtectedPortfolioRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/dashboard/portfolio/$id': typeof ProtectedDashboardPortfolioIdRoute
  '/_protected/dashboard/portfolio/': typeof ProtectedDashboardPortfolioIndexRoute
  '/_protected/dashboard/transaction/': typeof ProtectedDashboardTransactionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portfolio'
    | '/dashboard'
    | '/dashboard/portfolio/$id'
    | '/dashboard/portfolio'
    | '/dashboard/transaction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio'
    | '/dashboard'
    | '/dashboard/portfolio/$id'
    | '/dashboard/portfolio'
    | '/dashboard/transaction'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_auth/login'
    | '/_protected/portfolio'
    | '/_protected/dashboard/'
    | '/_protected/dashboard/portfolio/$id'
    | '/_protected/dashboard/portfolio/'
    | '/_protected/dashboard/transaction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/portfolio': {
      id: '/_protected/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof ProtectedPortfolioRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/transaction/': {
      id: '/_protected/dashboard/transaction/'
      path: '/dashboard/transaction'
      fullPath: '/dashboard/transaction'
      preLoaderRoute: typeof ProtectedDashboardTransactionIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/portfolio/': {
      id: '/_protected/dashboard/portfolio/'
      path: '/dashboard/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof ProtectedDashboardPortfolioIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/portfolio/$id': {
      id: '/_protected/dashboard/portfolio/$id'
      path: '/dashboard/portfolio/$id'
      fullPath: '/dashboard/portfolio/$id'
      preLoaderRoute: typeof ProtectedDashboardPortfolioIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedPortfolioRoute: typeof ProtectedPortfolioRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedDashboardPortfolioIdRoute: typeof ProtectedDashboardPortfolioIdRoute
  ProtectedDashboardPortfolioIndexRoute: typeof ProtectedDashboardPortfolioIndexRoute
  ProtectedDashboardTransactionIndexRoute: typeof ProtectedDashboardTransactionIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPortfolioRoute: ProtectedPortfolioRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedDashboardPortfolioIdRoute: ProtectedDashboardPortfolioIdRoute,
  ProtectedDashboardPortfolioIndexRoute: ProtectedDashboardPortfolioIndexRoute,
  ProtectedDashboardTransactionIndexRoute:
    ProtectedDashboardTransactionIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
